brew "wget"
brew "git"
brew "gnupg"
brew "pinentry-mac"
brew "git-crypt"
brew "pass"
brew "pass-otp"
brew "gnupg "
brew "yubikey-personalization"
brew "hopenpgp-tools"
brew "ykman"

cask "docker"
brew "tilt"
brew "earthly"

cask "xbar"
cask "ccmenu"
cask "divvy"
cask "visual-studio-code"
cask "iterm2"
cask "tunnelblick"
brew "powerline-go"
